import React from "react";
import { IconDefaultProps } from "./props";

import { IconApplication, IconHome, IconHomeFill, IconMore, IconMoreLine } from "./Nav";
import {
  IconRefresh,
  IconAvatar,
  IconCollection,
  IconConfigSetting,
  IconDark,
  IconDarkFill,
  IconFemale,
  IconLight,
  IconMale,
  IconPreviewClose,
  IconPreviewOpen,
  IconSearch,
  IconSetting,
  IconShare,
  IconTag,
  IconTranslate,
  IconLightFill,
  IconSettingFill,
} from "./Interface";
import {
  IconImage,
  IconLoop,
  IconVideoFullWidth,
  IconVideoPause,
  IconVideoPlay,
  IconVideoSmallScreen,
  IconVolume,
  IconVolumeMuted,
} from "./Media";
import {
  IconAnnouncement,
  IconAudioFile,
  IconBook,
  IconClipboard,
  IconCodeFile,
  IconCodeFolder,
  IconDocument,
  IconDownload,
  IconUpload,
  IconEmail,
  IconEmailDownload,
  IconEmailFail,
  IconEmailOpen,
  IconEmailPush,
  IconEmailSuccess,
  IconFile,
  IconFileAdd,
  IconFolder,
  IconFolderAdd,
  IconFolderDownload,
  IconFolderUpload,
  IconFormattingBrush,
  IconInstruction,
  IconLink,
  IconListView,
  IconLog,
  IconNotePad,
  IconPlan,
  IconSchedule,
  IconStarFile,
  IconTextFile,
  IconWebAdd,
  IconWebPage,
  IconCalendar,
  IconTextScan,
  IconCode,
} from "./File";

import {
  IconBankCard,
  IconCommodity,
  IconConsume,
  IconCoupon,
  IconDollar,
  IconTicket,
} from "./Ecommerce";
import {
  IconAttention,
  IconAttentionFill,
  IconAttentionStroke,
  IconCheck,
  IconCheckFill,
  IconCheckStroke,
  IconError,
  IconErrorFill,
  IconErrorStroke,
  IconHourglassEmpty,
  IconHourglassFull,
  IconIncrease,
  IconInfo,
  IconInfoFill,
  IconInfoStroke,
  IconQuestion,
  IconQuestionFill,
  IconQuestionStroke,
} from "./State";
import {
  IconAdd,
  IconDec,
  IconAdjustment,
  IconAhead,
  IconAlphabeticalSorting,
  IconAlphabeticalSortingReverse,
  IconBack,
  IconBrightness,
  IconClear,
  IconClearFormate,
  IconClipEdit,
  IconClose,
  IconColorPicker,
  IconCopy,
  IconCursorMove,
  IconCursorMoveFill,
  IconDashAdd,
  IconDelete,
  IconDrag,
  IconEdit,
  IconFilter,
  IconLastStep,
  IconLastStepFill,
  IconLayerBack,
  IconLayerFront,
  IconLike,
  IconLikeFill,
  IconLineBreak,
  IconLock,
  IconMergeCells,
  IconNextStep,
  IconNextStepFill,
  IconOut,
  IconPen,
  IconQuote,
  IconReload,
  IconScan,
  IconSort,
  IconSortAscending,
  IconSortDescending,
  IconSplitCells,
  IconSquareAdd,
  IconStar,
  IconStarFill,
  IconSwitchGear,
  IconToggle,
  IconUndo,
  IconUnlock,
  IconZoomIn,
  IconZoomInArrow,
  IconZoomInBtn,
  IconZoomOut,
  IconZoomOutArrow,
  IconZoomOutBtn,
} from "./Operate";
import {
  IconAlignBottom,
  IconAlignBottomCenter,
  IconAlignBottomLeft,
  IconAlignBottomRight,
  IconAlignHorizontalBottom,
  IconAlignHorizontalCenter,
  IconAlignHorizontalTop,
  IconAlignHorizontally,
  IconAlignLeft,
  IconAlignLeftBottom,
  IconAlignLeftCenter,
  IconAlignLeftTop,
  IconAlignRight,
  IconAlignRightBottom,
  IconAlignRightCenter,
  IconAlignRightTop,
  IconAlignTop,
  IconAlignTopCenter,
  IconAlignTopLeft,
  IconAlignTopRight,
  IconAlignVerticalCenter,
  IconAlignVerticalLeft,
  IconAlignVerticalRight,
  IconAlignVertically,
  IconAlphabetList,
  IconCheckList,
  IconCheckboxList,
  IconDeleteStrike,
  IconDropShadowDown,
  IconDropShadowLeft,
  IconDropShadowRight,
  IconDropShadowUp,
  IconFlipHorizontally,
  IconFlipVertically,
  IconFontSize,
  IconIndentLeft,
  IconIndentRight,
  IconInnerShadowDown,
  IconInnerShadowLeft,
  IconInnerShadowRight,
  IconInnerShadowUp,
  IconLayer,
  IconLineHeight,
  IconLineWidth,
  IconMask,
  IconNumberList,
  IconRadioList,
  IconTail,
  IconTextAlignCenter,
  IconTextAlignJustify,
  IconTextAlignLeft,
  IconTextAlignMiddle,
  IconTextAlignRight,
  IconTextBold,
  IconTextItalic,
  IconTextUnderline,
  IconTitleH1,
  IconTitleH2,
  IconTitleH3,
} from "./Style";
import {
  IconArrow,
  IconArrowDouble,
  IconArrowLine,
  IconArrowNav,
  IconArrowTo,
  IconArrowTriangle,
} from "./Arrow";
import { IconCamera, IconApple } from "./DeviceTool";



const iconMap = {
  // Navigation
  home: IconHome,
  'home-fill': IconHomeFill,
  application: IconApplication,
  more: IconMore,
  'more-line': IconMoreLine,
  search: IconSearch,

  // Interface
  refresh: IconRefresh,
  female: IconFemale,
  male: IconMale,
  'preview-open': IconPreviewOpen,
  'preview-close': IconPreviewClose,
  avatar: IconAvatar,
  tag: IconTag,
  setting: IconSetting,
  'config-setting': IconConfigSetting,
  collection: IconCollection,
  share: IconShare,
  translate: IconTranslate,
  light: IconLight,
  dark: IconDark,
  'light-fill': IconLightFill,
  'dark-fill': IconDarkFill,
  'setting-fill': IconSettingFill,
  // Media
  image: IconImage,
  'video-play': IconVideoPlay,
  'video-pause': IconVideoPause,
  volume: IconVolume,
  'volume-muted': IconVolumeMuted,
  'video-small-screen': IconVideoSmallScreen,
  'video-full-width': IconVideoFullWidth,
  loop: IconLoop,

  // File
  file: IconFile,
  download: IconDownload,
  upload: IconUpload,
  'web-add': IconWebAdd,
  announcement: IconAnnouncement,
  'audio-file': IconAudioFile,
  book: IconBook,
  clipboard: IconClipboard,
  document: IconDocument,
  email: IconEmail,
  'email-download': IconEmailDownload,
  'email-push': IconEmailPush,
  'email-success': IconEmailSuccess,
  'email-fail': IconEmailFail,
  'email-open': IconEmailOpen,
  'file-add': IconFileAdd,
  'code-file': IconCodeFile,
  'star-file': IconStarFile,
  'text-file': IconTextFile,
  'text-scan': IconTextScan,
  folder: IconFolder,
  'code-folder': IconCodeFolder,
  'folder-download': IconFolderDownload,
  'folder-add': IconFolderAdd,
  'folder-upload': IconFolderUpload,
  'formatting-brush': IconFormattingBrush,
  instruction: IconInstruction,
  'list-view': IconListView,
  link: IconLink,
  log: IconLog,
  'note-pad': IconNotePad,
  schedule: IconSchedule,
  'web-page': IconWebPage,
  plan: IconPlan,
  calendar: IconCalendar,
  code: IconCode,

  // Ecommerce
  coupon: IconCoupon,
  ticket: IconTicket,
  'bank-card': IconBankCard,
  consume: IconConsume,
  commodity: IconCommodity,
  dollar: IconDollar,

  // State
  'check-stroke': IconCheckStroke,
  'check-fill': IconCheckFill,
  check: IconCheck,
  'error-stroke': IconErrorStroke,
  'error-fill': IconErrorFill,
  error: IconError,
  'info-stroke': IconInfoStroke,
  'info-fill': IconInfoFill,
  info: IconInfo,
  'attention-stroke': IconAttentionStroke,
  'attention-fill': IconAttentionFill,
  attention: IconAttention,
  'question-stroke': IconQuestionStroke,
  'question-fill': IconQuestionFill,
  question: IconQuestion,
  'hourglass-empty': IconHourglassEmpty,
  'hourglass-full': IconHourglassFull,
  increase: IconIncrease,

  // Operate
  'switch-gear': IconSwitchGear,
  toggle: IconToggle,
  reload: IconReload,
  undo: IconUndo,
  sort: IconSort,
  'sort-descending': IconSortDescending,
  'sort-ascending': IconSortAscending,
  back: IconBack,
  'last-step': IconLastStep,
  'last-step-fill': IconLastStepFill,
  'next-step': IconNextStep,
  'next-step-fill': IconNextStepFill,
  ahead: IconAhead,
  drag: IconDrag,
  add: IconAdd,
  dec: IconDec,
  'square-add': IconSquareAdd,
  'dash-add': IconDashAdd,
  clear: IconClear,
  delete: IconDelete,
  copy: IconCopy,
  close: IconClose,
  'color-picker': IconColorPicker,
  'zoom-in-arrow': IconZoomInArrow,
  'zoom-out-arrow': IconZoomOutArrow,
  'zoom-in': IconZoomIn,
  'zoom-out': IconZoomOut,
  'zoom-in-btn': IconZoomInBtn,
  'zoom-out-btn': IconZoomOutBtn,
  out: IconOut,
  adjustment: IconAdjustment,
  'alphabetical-sorting': IconAlphabeticalSorting,
  'alphabetical-sorting-reverse': IconAlphabeticalSortingReverse,
  brightness: IconBrightness,
  layer: IconLayer,
  'layer-front': IconLayerFront,
  'layer-back': IconLayerBack,
  'clear-formate': IconClearFormate,
  edit: IconEdit,
  'clip-edit': IconClipEdit,
  filter: IconFilter,
  lock: IconLock,
  unlock: IconUnlock,
  'merge-cells': IconMergeCells,
  'split-cells': IconSplitCells,
  'cursor-move': IconCursorMove,
  'cursor-move-fill': IconCursorMoveFill,
  'line-break': IconLineBreak,
  quote: IconQuote,
  scan: IconScan,
  like: IconLike,
  'like-fill': IconLikeFill,
  star: IconStar,
  'star-fill': IconStarFill,
  pen: IconPen,

  // Arrow
  'arrow-line': IconArrowLine,
  'arrow-double': IconArrowDouble,
  arrow: IconArrow,
  'arrow-triangle': IconArrowTriangle,
  'arrow-to': IconArrowTo,
  'arrow-nav': IconArrowNav,

  // Device
  camera: IconCamera,
  apple: IconApple,

  // Style
  'align-bottom': IconAlignBottom,
  'align-top': IconAlignTop,
  'align-left': IconAlignLeft,
  'align-right': IconAlignRight,
  'align-horizontally': IconAlignHorizontally,
  'align-vertically': IconAlignVertically,
  'text-align-left': IconTextAlignLeft,
  'text-align-right': IconTextAlignRight,
  'text-align-center': IconTextAlignCenter,
  'text-align-justify': IconTextAlignJustify,
  'text-align-middle': IconTextAlignMiddle,
  'align-bottom-center': IconAlignBottomCenter,
  'align-bottom-left': IconAlignBottomLeft,
  'align-bottom-right': IconAlignBottomRight,
  'align-horizontal-bottom': IconAlignHorizontalBottom,
  'align-horizontal-center': IconAlignHorizontalCenter,
  'align-horizontal-top': IconAlignHorizontalTop,
  'align-left-bottom': IconAlignLeftBottom,
  'align-left-center': IconAlignLeftCenter,
  'align-left-top': IconAlignLeftTop,
  'align-right-bottom': IconAlignRightBottom,
  'align-right-center': IconAlignRightCenter,
  'align-right-top': IconAlignRightTop,
  'align-top-center': IconAlignTopCenter,
  'align-top-left': IconAlignTopLeft,
  'align-top-right': IconAlignTopRight,
  'align-vertical-left': IconAlignVerticalLeft,
  'align-vertical-center': IconAlignVerticalCenter,
  'align-vertical-right': IconAlignVerticalRight,
  'flip-horizontally': IconFlipHorizontally,
  'flip-vertically': IconFlipVertically,
  'font-size': IconFontSize,
  'line-height': IconLineHeight,
  'text-bold': IconTextBold,
  'text-italic': IconTextItalic,
  'text-underline': IconTextUnderline,
  'line-width': IconLineWidth,
  'title-h1': IconTitleH1,
  'title-h2': IconTitleH2,
  'title-h3': IconTitleH3,
  'indent-left': IconIndentLeft,
  'indent-right': IconIndentRight,
  'drop-shadow-up': IconDropShadowUp,
  'drop-shadow-down': IconDropShadowDown,
  'drop-shadow-left': IconDropShadowLeft,
  'drop-shadow-right': IconDropShadowRight,
  'inner-shadow-up': IconInnerShadowUp,
  'inner-shadow-down': IconInnerShadowDown,
  'inner-shadow-left': IconInnerShadowLeft,
  'inner-shadow-right': IconInnerShadowRight,
  'check-list': IconCheckList,
  'alphabet-list': IconAlphabetList,
  'checkbox-list': IconCheckboxList,
  'radio-list': IconRadioList,
  'number-list': IconNumberList,
  mask: IconMask,
  'delete-strike': IconDeleteStrike,
  tail: IconTail,
};

const Icon: React.FC<IconDefaultProps> = ({ name, ...restProps }) => {
  const IconComponent = iconMap[name];
  if (!IconComponent) {
    console.warn(`Icon "${name}" not found`);
    return <IconError {...restProps} />;
  }
  return <IconComponent {...restProps} />;
};

export default Icon;
